# latexmk configuration (read automatically by Overleaf and by ./build.sh)
$pdf_mode = 1;            # pdflatex
$bibtex_use = 2;          # run biber when needed
$pdflatex = 'pdflatex -interaction=nonstopmode -file-line-error -synctex=1 %O %S';
$makeindex = 'makeindex %O -o %D %S';
$max_repeat = 6;
