"""Write the TikZ source of the Chapter 1 scenario figure.

Usage: ``python3 gen_ch01_scenario.py`` (from any directory).

The scenario comes from ``code/ch01_scenario.py`` with the fixed seed
``BOOK_SEED``; the script writes ``figures/ch01/scenario.tex`` and prints
the per-step trace that the chapter quotes.  Standard library only.
"""

from __future__ import annotations

import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))

import ch01_scenario as sc  # noqa: E402

OUT = os.path.join(HERE, "..", "..", "figures", "ch01", "scenario.tex")

WIDTH, HEIGHT, DRONES, DENSITY = 12, 8, 3, 0.15
NAMES = "ABC"
PATH_STYLES = ["sbpath", "sbpathalt", "sbpath,draw=sbAgentC,densely dashdotted"]
AGENT_STYLES = ["sbagentA", "sbagentB", "sbagentC"]
PREDICTION_STEPS = (2, 4, 6, 8)  # predicted intruder positions to draw


def centre(cell):
    return f"({cell[0] + 0.5:.2f},{cell[1] + 0.5:.2f})"


def tikz(scenario, paths):
    intr = scenario.intruder
    conflicts = sc.find_conflicts(paths)
    encounters = sc.intruder_encounters(scenario, paths)
    lines = []
    add = lines.append
    add("% Generated by code/figures/gen_ch01_scenario.py "
        f"(seed {scenario.seed}); do not edit by hand.")
    add(r"\begin{tikzpicture}[scale=0.62]")
    add(r"\drawgrid{%d}{%d}" % (scenario.width, scenario.height))
    for x, y in sorted(scenario.obstacles):
        add(r"\gridobstacle{%d}{%d}" % (x, y))
    # Predicted straight-line motion of the intruder with growing uncertainty.
    for t in PREDICTION_STEPS:
        x, y = intr.position_at(t)
        r = 0.15 + 0.07 * t
        add(r"\fill[sbRed!12] (%.2f,%.2f) circle (%.2f);" % (x, y, r))
    last = intr.position_at(PREDICTION_STEPS[-1])
    add(r"\draw[draw=sbIntruder,densely dotted,thick] (%.2f,%.2f) -- (%.2f,%.2f);"
        % (*intr.position, *last))
    for t in PREDICTION_STEPS:
        x, y = intr.position_at(t)
        r = 0.15 + 0.07 * t
        add(r"\draw[draw=sbIntruder,dashed,thin] (%.2f,%.2f) circle (%.2f);" % (x, y, r))
        add(r"\node[sbannot,text=sbIntruder,font=\tiny] at (%.2f,%.2f) {$t{=}%d$};"
            % (x + r + 0.45, y, t))
    # Planned paths of the controlled drones.
    for i, path in enumerate(paths):
        pts = " -- ".join(centre(c) for c in path)
        add(r"\draw[%s] %s;" % (PATH_STYLES[i], pts))
    # Markers of the planned conflict and of the predicted encounter.
    for c in conflicts:
        cell = c.where if c.kind == "vertex" else c.where[0]
        a, b = (NAMES[k] for k in c.agents)
        add(r"\draw[draw=sbRed,line width=1.2pt] (%d.1,%d.1) rectangle (%d.9,%d.9);"
            % (cell[0], cell[1], cell[0], cell[1]))
        add(r"\node[sbannot,text=sbRed,anchor=south west,font=\scriptsize] "
            r"at (%.2f,%.2f) {%s/%s, $t{=}%d$};"
            % (cell[0] + 0.95, cell[1] + 0.95, a, b, c.time))
    if encounters:
        e = min(encounters, key=lambda e: e.distance)
        cell = sc.position_on_path(paths[e.drone], e.time)
        add(r"\draw[draw=sbRed,line width=1.2pt,dashed] %s circle (0.62);" % centre(cell))
        add(r"\node[sbannot,text=sbRed,anchor=south,font=\scriptsize] "
            r"at (%.2f,%.2f) {%s, $t{=}%d$};"
            % (cell[0] + 0.5, cell[1] + 1.2, NAMES[e.drone], e.time))
    # Starts (circles), goals (squares), intruder and its velocity.
    for i, (s, g) in enumerate(zip(scenario.starts, scenario.goals)):
        add(r"\node[%s] at %s {%s};" % (AGENT_STYLES[i], centre(s), NAMES[i]))
        add(r"\node[%s,rectangle,fill=white] at %s {%s};"
            % (AGENT_STYLES[i], centre(g), NAMES[i]))
    vx, vy = intr.velocity
    add(r"\draw[sbvec,draw=sbIntruder] (%.2f,%.2f) -- ++(%.2f,%.2f);"
        % (*intr.position, 2.0 * vx, 2.0 * vy))
    add(r"\node[sbintruder] at (%.2f,%.2f) {?};" % intr.position)
    # Legend.
    lx, ly = scenario.width + 0.9, scenario.height - 0.5
    add(r"\begin{scope}[font=\footnotesize]")
    for i in range(len(paths)):
        add(r"\node[%s] at (%.2f,%.2f) {%s};" % (AGENT_STYLES[i], lx, ly - 0.9 * i, NAMES[i]))
        add(r"\node[%s,rectangle,fill=white] at (%.2f,%.2f) {%s};"
            % (AGENT_STYLES[i], lx + 0.75, ly - 0.9 * i, NAMES[i]))
        add(r"\draw[%s] (%.2f,%.2f) -- ++(1.1,0);" % (PATH_STYLES[i], lx + 1.35, ly - 0.9 * i))
        add(r"\node[sbannot,anchor=west] at (%.2f,%.2f) {drone %s: start, goal, planned path};"
            % (lx + 2.6, ly - 0.9 * i, NAMES[i]))
    k = len(paths)
    add(r"\node[sbintruder] at (%.2f,%.2f) {?};" % (lx, ly - 0.9 * k))
    add(r"\draw[sbvec,draw=sbIntruder] (%.2f,%.2f) -- ++(1.0,0);" % (lx + 0.45, ly - 0.9 * k))
    add(r"\node[sbannot,anchor=west] at (%.2f,%.2f) {intruder and its velocity};"
        % (lx + 2.6, ly - 0.9 * k))
    add(r"\draw[draw=sbIntruder,densely dotted,thick] (%.2f,%.2f) -- ++(1.2,0);"
        % (lx - 0.3, ly - 0.9 * (k + 1)))
    add(r"\draw[draw=sbIntruder,dashed,thin] (%.2f,%.2f) circle (0.32);"
        % (lx + 1.5, ly - 0.9 * (k + 1)))
    add(r"\node[sbannot,anchor=west] at (%.2f,%.2f) {predicted motion, growing uncertainty};"
        % (lx + 2.6, ly - 0.9 * (k + 1)))
    add(r"\draw[draw=sbRed,line width=1.2pt] (%.2f,%.2f) rectangle ++(0.7,0.7);"
        % (lx - 0.35, ly - 0.9 * (k + 2) - 0.35))
    add(r"\draw[draw=sbRed,line width=1.2pt,dashed] (%.2f,%.2f) circle (0.4);"
        % (lx + 1.5, ly - 0.9 * (k + 2)))
    add(r"\node[sbannot,anchor=west] at (%.2f,%.2f) {planned conflict, predicted encounter};"
        % (lx + 2.6, ly - 0.9 * (k + 2)))
    add(r"\fill[sbobstacle] (%.2f,%.2f) rectangle ++(0.7,0.7);"
        % (lx - 0.35, ly - 0.9 * (k + 3) - 0.35))
    add(r"\node[sbannot,anchor=west] at (%.2f,%.2f) {blocked cell};"
        % (lx + 2.6, ly - 0.9 * (k + 3)))
    add(r"\end{scope}")
    add(r"\end{tikzpicture}")
    return "\n".join(lines) + "\n"


def trace_rows(scenario, paths):
    """LaTeX rows: step, cells of the drones, intruder position, distances."""
    intr = scenario.intruder
    horizon = max(len(p) for p in paths)
    rows = []
    for t in range(horizon + 1):
        cells = [sc.position_on_path(p, t) for p in paths]
        px, py = intr.position_at(t)
        dists = [math.hypot(px - cx, py - cy)
                 for cx, cy in (sc.cell_centre(c) for c in cells)]
        cell_txt = " & ".join("(%d,%d)" % c for c in cells)
        dist_txt = " & ".join("%.2f" % d for d in dists)
        rows.append("%d & %s & (%.2f, %.2f) & %s\\\\" % (t, cell_txt, px, py, dist_txt))
    return "\n".join(rows)


def main():
    scenario = sc.generate(WIDTH, HEIGHT, DRONES, DENSITY, seed=sc.BOOK_SEED)
    paths = sc.plan_independently(scenario)
    with open(OUT, "w", encoding="ascii") as f:
        f.write(tikz(scenario, paths))
    print("wrote", os.path.normpath(OUT))
    print(sc.describe(scenario))
    print("--- trace rows (t, A, B, C, intruder, d_A, d_B, d_C) ---")
    print(trace_rows(scenario, paths))


if __name__ == "__main__":
    main()
