"""Generate figures/ch03/wavefront.tex: Dijkstra's wavefront on a grid.

Runs dijkstra() from a single source on an 8-connected grid with a wall and
a block, then colours every free cell by the band floor(g) of its distance
and draws the band boundaries as contour lines.  NumPy-free apart from the
chapter module; deterministic (no randomness).  Run from Overleaf/:

    python3 code/figures/gen_ch03_wavefront.py
"""

import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from ch03_dijkstra import GridGraph, dijkstra  # noqa: E402

ROWS, COLS = 11, 18
SOURCE = (5, 3)
OUT = os.path.join(os.path.dirname(HERE), "..", "figures", "ch03", "wavefront.tex")


def build_cells():
    cells = [[0] * COLS for _ in range(ROWS)]
    for r in range(2, ROWS):            # a wall with a gap at the top
        cells[r][10] = 1
    for r in (4, 5, 6):                 # a small block near the source
        for c in (6, 7):
            cells[r][c] = 1
    return cells


def main():
    cells = build_cells()
    grid = GridGraph(cells, 8)
    dist, _ = dijkstra(grid, SOURCE)
    band = {v: int(math.floor(g + 1e-9)) for v, g in dist.items()}
    max_band = max(band.values())

    def y(r):
        return ROWS - 1 - r

    lines = ["% Generated by code/figures/gen_ch03_wavefront.py -- do not edit",
             "\\begin{tikzpicture}[scale=0.52]"]
    for r in range(ROWS):
        for c in range(COLS):
            if cells[r][c]:
                lines.append("\\fill[sbobstacle] (%d,%d) rectangle ++(1,1);" % (c, y(r)))
            elif (r, c) in band:
                shade = 8 if band[(r, c)] % 2 == 0 else 36
                lines.append("\\fill[sbBlue!%d] (%d,%d) rectangle ++(1,1);" % (shade, c, y(r)))
    lines.append("\\drawgrid{%d}{%d}" % (COLS, ROWS))
    # contour lines between cells of different bands
    for r in range(ROWS):
        for c in range(COLS):
            b = band.get((r, c))
            if b is None:
                continue
            if c + 1 < COLS and band.get((r, c + 1)) not in (None, b):
                lines.append("\\draw[sbBlue!85!black,line width=0.9pt] (%d,%d) -- ++(0,1);" % (c + 1, y(r)))
            if r + 1 < ROWS and band.get((r + 1, c)) not in (None, b):
                lines.append("\\draw[sbBlue!85!black,line width=0.9pt] (%d,%d) -- ++(1,0);" % (c, y(r)))
    # band labels along the source row and on the far side of the wall
    for c in range(COLS):
        v = (SOURCE[0], c)
        if v in band and v != SOURCE and cells[SOURCE[0]][c] == 0 and c < 10:
            lines.append("\\node[font=\\scriptsize,text=sbBlue!60!black] at (%.1f,%.1f) {%d};"
                         % (c + 0.5, y(SOURCE[0]) + 0.5, band[v]))
    for r, c in [(0, 12), (2, 14), (5, 15), (8, 14), (10, 12), (3, 17), (10, 16)]:
        if (r, c) in band:
            lines.append("\\node[font=\\scriptsize,text=sbBlue!60!black] at (%.1f,%.1f) {%d};"
                         % (c + 0.5, y(r) + 0.5, band[(r, c)]))
    lines.append("\\node[sbstart] at (%.1f,%.1f) {};" % (SOURCE[1] + 0.5, y(SOURCE[0]) + 0.5))
    lines.append("\\node[sbannot,anchor=south] at (%.1f,%.1f) {source $s$};" % (SOURCE[1] + 0.5, y(SOURCE[0]) + 1.05))
    lines.append("\\node[sbannot,anchor=north] at (%.1f,-0.25) {numbers: $\\lfloor \\gcost \\rfloor$, the wave settles band $k$ before band $k+1$};" % (COLS / 2))
    lines.append("\\end{tikzpicture}")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(OUT), "max band", max_band, "cells", len(dist))


if __name__ == "__main__":
    main()
