"""Generate the data and figures of chapter 14 (DWA) from code/ch14_dwa.py.

Writes (paths relative to Overleaf/):
    figures/data/ch14-corridor-<setting>.dat   closed-loop trajectories in the
    figures/data/ch14-utrap-<setting>.dat      corridor and the U-trap for the
                                               weight settings heading,
                                               clearance, velocity (columns
                                               t x y; at most MAX_STEPS steps)
    figures/data/ch14-utrap-path.dat           U-trap with the default weights
                                               and the heading term taken from
                                               a global path (the remedy)
    figures/ch14/experiment.tex                the two-panel pgfplots figure
    figures/ch14/example-window.tex            velocity space of the worked
                                               example (window, admissible
                                               region, candidates, choice)
    figures/ch14/example-scene.tex             workspace of the worked example
                                               with the rollouts and the
                                               closed-loop trajectory
and prints the rows of the tables of the chapter (candidate scores, closed-
loop trace, metrics per weight setting).  Everything is deterministic (no
randomness is involved).

Run from Overleaf/:   python3 code/figures/gen_ch14_traj.py
"""
import math
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from ch14_dwa import (Box, Disc, DwaParams, UTRAP_WAYPOINTS, WEIGHT_SETTINGS,  # noqa: E402
                      admissible_speed, corridor_scene, dwa_command, evaluate,
                      free_distance, simulate, utrap_scene, worked_example)

ROOT = os.path.join(os.path.dirname(HERE), "..")
DATA = os.path.join(ROOT, "figures", "data")
FIGS = os.path.join(ROOT, "figures", "ch14")
MAX_STEPS = 80          # 20 s of simulated time per run
STYLES = {"heading": "sbBlue,thick", "clearance": "sbOrange,thick,dashed",
          "velocity": "sbPurple,thick,dotted"}
LABELS = {"heading": "heading-dominant $(0.8,0.1,0.1)$",
          "clearance": "clearance-dominant $(0.2,0.6,0.2)$",
          "velocity": "velocity-dominant $(0.2,0.2,0.6)$"}


def write_dat(name, traj, dt):
    path = os.path.join(DATA, name)
    with open(path, "w") as fh:
        fh.write("t x y\n")
        for k, p in enumerate(traj):
            fh.write("%.3f %.4f %.4f\n" % (k * dt, p[0], p[1]))
    return path


def polygon(points):
    return " ".join("(%.4f,%.4f)" % (x, y) for x, y in points)


def circle_points(c, r, n=48):
    return [(c[0] + r * math.cos(2 * math.pi * k / n), c[1] + r * math.sin(2 * math.pi * k / n))
            for k in range(n)]


def obstacle_plots(obstacles):
    out = []
    for ob in obstacles:
        if isinstance(ob, Box):
            pts = [(ob.lo[0], ob.lo[1]), (ob.hi[0], ob.lo[1]), (ob.hi[0], ob.hi[1]), (ob.lo[0], ob.hi[1])]
        else:
            pts = circle_points(ob.centre, ob.radius)
        out.append("\\addplot[fill=sbObstacle,draw=black!40,thin,forget plot] coordinates {%s} -- cycle;"
                   % polygon(pts))
    return "\n".join(out)


def run_scenes():
    metrics = []
    runs = {}
    for scene_name, scene in (("corridor", corridor_scene), ("utrap", utrap_scene)):
        for setting, weights in [("default", DwaParams().weights)] + list(WEIGHT_SETTINGS.items()):
            p0, v0, goal, obstacles = scene()
            prm = DwaParams(weights=weights)
            run = simulate(p0, v0, goal, obstacles, prm, max_steps=300)
            metrics.append((scene_name, setting, run))
            if setting != "default":
                short = simulate(*scene(), prm, max_steps=MAX_STEPS)
                runs[(scene_name, setting)] = short
                write_dat("ch14-%s-%s.dat" % (scene_name, setting), short["traj"], prm.dt)
    p0, v0, goal, obstacles = utrap_scene()
    run = simulate(p0, v0, goal, obstacles, DwaParams(), max_steps=300,
                   waypoints=UTRAP_WAYPOINTS, lookahead=1.0)
    metrics.append(("utrap", "default + global path", run))
    write_dat("ch14-utrap-path.dat", run["traj"], DwaParams().dt)
    return metrics


def write_experiment_figure():
    corridor = corridor_scene()[3]
    utrap = utrap_scene()[3]
    lines = []
    lines.append("% Generated by code/figures/gen_ch14_traj.py -- do not edit by hand.")
    lines.append("\\begin{tikzpicture}[font=\\footnotesize]")
    lines.append("\\begin{groupplot}[group style={group size=2 by 1,horizontal sep=1.2cm},"
                 "width=0.5\\textwidth,axis equal image,"
                 "xlabel={$x$ [m]},ylabel={$y$ [m]},grid=major,grid style={black!10},"
                 "unbounded coords=jump,clip=true]")
    # corridor panel
    lines.append("\\nextgroupplot[xmin=-1,xmax=7,ymin=-3.2,ymax=2.2,title={(a) corridor with a pillar}]")
    lines.append(obstacle_plots(corridor))
    for setting in STYLES:
        lines.append("\\addplot[%s] table[x=x,y=y]{figures/data/ch14-corridor-%s.dat};"
                     % (STYLES[setting], setting))
    lines.append("\\addplot[only marks,mark=*,mark options={draw=sbGreen,fill=sbGreen!30},forget plot] coordinates {(0,0)};")
    lines.append("\\addplot[only marks,mark=*,mark options={draw=sbRed,fill=sbRed!30},forget plot] coordinates {(6,0)};")
    lines.append("\\node[sbannot] at (axis cs:0,0.45) {start};")
    lines.append("\\node[sbannot] at (axis cs:6,0.45) {goal};")
    # U-trap panel
    lines.append("\\nextgroupplot[xmin=-1,xmax=8,ymin=-3.2,ymax=3.6,title={(b) U-shaped trap},"
                 "legend style={at={(-0.12,-0.28)},anchor=north,legend columns=2,font=\\scriptsize,"
                 "/tikz/every even column/.append style={column sep=0.4cm}}]")
    lines.append(obstacle_plots(utrap))
    for setting in STYLES:
        lines.append("\\addplot[%s] table[x=x,y=y]{figures/data/ch14-utrap-%s.dat};"
                     % (STYLES[setting], setting))
        lines.append("\\addlegendentry{%s}" % LABELS[setting])
    lines.append("\\addplot[sbGreen,thick,densely dashdotted] table[x=x,y=y]{figures/data/ch14-utrap-path.dat};")
    lines.append("\\addlegendentry{default $(0.6,0.2,0.2)$, heading from a global path}")
    lines.append("\\addplot[black!50,thin,dashed,forget plot] coordinates {%s};"
                 % " ".join("(%.1f,%.1f)" % (x, y) for x, y in UTRAP_WAYPOINTS))
    lines.append("\\addplot[only marks,mark=*,mark options={draw=sbGreen,fill=sbGreen!30},forget plot] coordinates {(0,0)};")
    lines.append("\\addplot[only marks,mark=*,mark options={draw=sbRed,fill=sbRed!30},forget plot] coordinates {(7,0)};")
    lines.append("\\node[sbannot] at (axis cs:0,0.5) {start};")
    lines.append("\\node[sbannot] at (axis cs:7,0.5) {goal};")
    lines.append("\\node[sbannot,text=black!50] at (axis cs:4.2,3.15) {global path};")
    lines.append("\\end{groupplot}")
    lines.append("\\end{tikzpicture}")
    with open(os.path.join(FIGS, "experiment.tex"), "w") as fh:
        fh.write("\n".join(lines) + "\n")


def write_example_figures():
    p, v_a, goal, obstacles, prm = worked_example()
    v_best, cands = dwa_command(p, v_a, obstacles, goal, prm, goal)
    # --- velocity space --------------------------------------------------
    boundary = []
    for k in range(361):
        phi = math.radians(k)
        d = np.array([math.cos(phi), math.sin(phi)])
        dist = free_distance(p, d, obstacles, prm.radius, prm.d_max)
        r = min(admissible_speed(dist, prm.a_brake, prm.dt), prm.v_max)
        boundary.append((r * d[0], r * d[1]))
    lo = v_a - prm.a_max * prm.dt
    hi = v_a + prm.a_max * prm.dt
    adm = [c for c in cands if c.admissible]
    inadm = [c for c in cands if not c.admissible]
    L = []
    L.append("% Generated by code/figures/gen_ch14_traj.py -- do not edit by hand.")
    L.append("\\begin{tikzpicture}[font=\\footnotesize]")
    L.append("\\begin{axis}[width=0.5\\textwidth,axis equal image,"
             "xmin=-0.35,xmax=2.25,ymin=-1.15,ymax=1.35,xlabel={$v_x$ [m/s]},ylabel={$v_y$ [m/s]},"
             "grid=major,grid style={black!10},clip=true]")
    L.append("\\addplot[fill=sbGreen!15,draw=sbGreen,thin,forget plot] coordinates {%s} -- cycle;" % polygon(boundary))
    L.append("\\addplot[black!60,dashed,thin,forget plot] coordinates {%s} -- cycle;" % polygon(circle_points((0.0, 0.0), prm.v_max, 90)))
    L.append("\\addplot[sbBlue,very thick,forget plot] coordinates {(%.2f,%.2f) (%.2f,%.2f) (%.2f,%.2f) (%.2f,%.2f)} -- cycle;"
             % (lo[0], lo[1], hi[0], lo[1], hi[0], hi[1], lo[0], hi[1]))
    L.append("\\addplot[only marks,mark=*,mark size=1.6pt,mark options={draw=sbBlue,fill=sbBlue!40},forget plot] coordinates {%s};"
             % polygon([(c.v[0], c.v[1]) for c in adm]))
    L.append("\\addplot[only marks,mark=x,mark size=2.6pt,thick,sbRed,forget plot] coordinates {%s};"
             % polygon([(c.v[0], c.v[1]) for c in inadm]))
    L.append("\\addplot[only marks,mark=square*,mark size=2.6pt,mark options={draw=black,fill=white},forget plot] coordinates {(%.2f,%.2f)};" % (v_a[0], v_a[1]))
    L.append("\\addplot[only marks,mark=star,mark size=4.5pt,very thick,sbOrange,forget plot] coordinates {(%.2f,%.2f)};" % (v_best[0], v_best[1]))
    L.append("\\node[sbannot,text=sbBlue] at (axis cs:1.0,0.68) {$V_d$};")
    L.append("\\node[sbannot,text=sbGreen] at (axis cs:-0.15,0.95) {$V_a$};")
    L.append("\\node[sbannot,text=black!60] at (axis cs:1.55,1.2) {$V_s$};")
    L.append("\\node[sbannot,anchor=north] at (axis cs:%.2f,%.2f) {$\\vel_a$};" % (v_a[0], v_a[1] - 0.06))
    L.append("\\node[sbannot,text=sbOrange,anchor=south west] at (axis cs:%.2f,%.2f) {chosen};" % (v_best[0] + 0.04, v_best[1] + 0.02))
    L.append("\\end{axis}")
    L.append("\\end{tikzpicture}")
    with open(os.path.join(FIGS, "example-window.tex"), "w") as fh:
        fh.write("\n".join(L) + "\n")
    # --- workspace ---------------------------------------------------------
    run = simulate(p, v_a, goal, obstacles, prm, max_steps=60)
    ob = obstacles[0]
    S = []
    S.append("% Generated by code/figures/gen_ch14_traj.py -- do not edit by hand.")
    S.append("\\begin{tikzpicture}[x=1.05cm,y=1.05cm,font=\\footnotesize]")
    S.append("\\draw[black!15,very thin] (-0.5,-1.2) grid[step=1] (5.5,1.3);")
    S.append("\\draw[->,black!50] (-0.5,0) -- (5.6,0) node[right,sbannot] {$x$};")
    S.append("\\draw[->,black!50] (0,-1.2) -- (0,1.4) node[above,sbannot] {$y$};")
    S.append("\\fill[sbobstacle] (%.2f,%.2f) circle (%.2f);" % (ob.centre[0], ob.centre[1], ob.radius))
    S.append("\\draw[black!50,dashed] (%.2f,%.2f) circle (%.2f);" % (ob.centre[0], ob.centre[1], ob.radius + prm.radius))
    for c in cands:
        end = p + c.v * prm.horizon
        style = "sbBlue!60,thin" if c.admissible else "sbRed!70,thin,densely dotted"
        S.append("\\draw[%s] (0,0) -- (%.3f,%.3f);" % (style, end[0], end[1]))
    end = p + v_best * prm.horizon
    S.append("\\draw[sbOrange,line width=1.6pt,-{Stealth[length=5pt]}] (0,0) -- (%.3f,%.3f);" % (end[0], end[1]))
    S.append("\\draw[sbpath,mark=*,mark size=1pt] plot coordinates {%s};" % polygon([(q[0], q[1]) for q in run["traj"]]))
    S.append("\\draw[sbGreen,thick] (0,0) circle (%.2f);" % prm.radius)
    S.append("\\node[sbgoal,label={[sbannot]above:goal}] at (%.1f,%.1f) {};" % (goal[0], goal[1]))
    S.append("\\node[sbannot,anchor=north east] at (-0.05,-0.25) {drone};")
    S.append("\\node[sbannot,text=sbOrange,anchor=south west] at (%.2f,%.2f) {chosen rollout};" % (end[0] + 0.05, end[1] + 0.05))
    S.append("\\node[sbannot,text=sbBlue,anchor=west] at (2.6,0.75) {closed-loop path, 13 steps};")
    S.append("\\node[sbannot,anchor=north] at (%.2f,%.2f) {obstacle};" % (ob.centre[0], ob.centre[1] - ob.radius - prm.radius - 0.05))
    S.append("\\end{tikzpicture}")
    with open(os.path.join(FIGS, "example-scene.tex"), "w") as fh:
        fh.write("\n".join(S) + "\n")
    return cands, run


def main():
    os.makedirs(DATA, exist_ok=True)
    os.makedirs(FIGS, exist_ok=True)
    metrics = run_scenes()
    write_experiment_figure()
    cands, run = write_example_figures()
    p, v_a, goal, obstacles, prm = worked_example()
    print("--- worked example: candidates (vx vy dist adm heading clearance velocity G) ---")
    for c in sorted(cands, key=lambda c: (-c.v[0], -c.v[1])):
        print("%.2f & %.2f & %.3f & %s & %.3f & %.3f & %.3f & %s \\\\" % (
            c.v[0], c.v[1], c.dist, "yes" if c.admissible else "no", c.heading, c.clearance,
            c.velocity, ("%.3f" % c.score) if c.admissible else "--"))
    print("--- worked example: closed-loop trace (step, p, v_a, chosen v, dist, h, c, s, G) ---")
    pos, vel = p.copy(), v_a.copy()
    for k in range(run["steps"]):
        v_new, cs = dwa_command(pos, vel, obstacles, goal, prm, goal)
        c = next(c for c in cs if np.allclose(c.v, v_new))
        print("%d & (%.2f, %.2f) & (%.2f, %.2f) & (%.2f, %.2f) & %.2f & %.3f & %.3f & %.3f & %.3f \\\\" % (
            k + 1, pos[0], pos[1], vel[0], vel[1], v_new[0], v_new[1], c.dist, c.heading,
            c.clearance, c.velocity, c.score))
        pos, vel = pos + v_new * prm.dt, v_new
    print("final position (%.3f, %.3f), path length %.3f m, min clearance %.3f m"
          % (run["traj"][-1][0], run["traj"][-1][1], run["path_length"], run["min_clearance"]))
    print("--- metrics per scene and weight setting ---")
    for scene, setting, r in metrics:
        end = r["traj"][-1]
        outcome = "collision" if r["collided"] else ("reached" if r["reached"] else "not reached")
        print("%s & %s & %s & %d & %.1f & %.2f & %.2f & (%.1f, %.1f) \\\\" % (
            scene, setting, outcome, r["steps"], r["path_length"], r["min_clearance"],
            r["mean_speed"], end[0], end[1]))


if __name__ == "__main__":
    main()
