"""Generate the grid figures of Chapter 4 from code/ch04_astar.py.

Writes one tikzpicture per file (no figure environment, no label):
    figures/ch04/example.tex   6x6 worked example: A* (Manhattan, larger g
                               first) next to Dijkstra (h = 0); Closed cells
                               grey with f (resp. g) and the expansion index,
                               Open cells blue, the returned path in blue.
    figures/ch04/tiebreak.tex  empty 20x20 grid, Manhattan heuristic:
                               Closed cells when ties are broken towards the
                               larger g (left) and towards the smaller g (right).

Run from Overleaf/:   python3 code/figures/gen_ch04_grids.py
"""
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from ch04_astar import (WORKED_GOAL, WORKED_START, astar_grid,  # noqa: E402
                        worked_example_grid)

FIGDIR = os.path.join(os.path.dirname(HERE), "..", "figures", "ch04")


def num(x):
    """Short number for a label: 7, 11, 9.83."""
    return "%d" % round(x) if abs(x - round(x)) < 1e-9 else "%.2f" % x


def panel(grid, res, start, goal, xshift, caption, labels=True, path=True,
          expanded_index=True):
    """TikZ scope for one grid; the goal counts as expanded (it was popped)."""
    rows, cols = grid.shape
    expanded = {}
    for i, e in enumerate(res.expansions, 1):
        expanded.setdefault(e.node, (i, e.f))          # first expansion
    out = ["\\begin{scope}[xshift=%.2fcm]" % xshift]
    for y in range(rows):
        for x in range(cols):
            if grid[y, x]:
                out.append("\\fill[sbobstacle] (%d,%d) rectangle ++(1,1);" % (x, y))
            elif (x, y) in expanded:
                out.append("\\fill[sbclosed] (%d,%d) rectangle ++(1,1);" % (x, y))
            elif (x, y) in res.open_nodes:
                out.append("\\fill[sbopen] (%d,%d) rectangle ++(1,1);" % (x, y))
    out.append("\\draw[black!40,very thin] (0,0) grid (%d,%d);" % (cols, rows))
    if path and res.path:
        pts = " -- ".join("(%.1f,%.1f)" % (x + 0.5, y + 0.5) for x, y in res.path)
        out.append("\\draw[sbpath,opacity=0.85] %s;" % pts)
    if labels:
        for (x, y), (i, f) in expanded.items():
            out.append("\\node[font=\\scriptsize\\bfseries] at (%.1f,%.1f) {%s};"
                       % (x + 0.5, y + 0.5, num(f)))
            if expanded_index:
                out.append("\\node[font=\\tiny,text=sbGray,anchor=north west,inner sep=1pt]"
                           " at (%d,%d) {%d};" % (x, y + 1, i))
        for (x, y) in sorted(res.open_nodes):       # f = g + h of Open nodes
            out.append("\\node[font=\\scriptsize,text=sbBlue] at (%.1f,%.1f) {%s};"
                       % (x + 0.5, y + 0.5, num(res.open_f[(x, y)])))
    sx, sy = start
    gx, gy = goal
    out.append("\\draw[sbStart,line width=1.4pt] (%d,%d) rectangle ++(1,1);" % (sx, sy))
    out.append("\\draw[sbGoal,line width=1.4pt] (%d,%d) rectangle ++(1,1);" % (gx, gy))
    out.append("\\node[font=\\tiny,text=sbStart,anchor=south east,inner sep=1pt] at (%d,%d) {S};"
               % (sx + 1, sy))
    out.append("\\node[font=\\tiny,text=sbGoal,anchor=south east,inner sep=1pt] at (%d,%d) {G};"
               % (gx + 1, gy))
    out.append("\\node[sbannot,text=black,anchor=north,align=center] at (%.1f,-0.15) {%s};"
               % (cols / 2.0, caption))
    out.append("\\end{scope}")
    return out


def with_open_f(res, h):
    """Attach f = g + h of every Open node to the result (for the labels)."""
    res.open_f = {n: res.g[n] + h(n) for n in res.open_nodes}
    return res


def write(name, lines):
    path = os.path.join(FIGDIR, name)
    with open(path, "w") as f:
        f.write("% Generated by code/figures/gen_ch04_grids.py -- do not edit\n")
        f.write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(path))


def example_figure():
    from ch04_astar import manhattan
    grid = worked_example_grid()
    s, z = WORKED_START, WORKED_GOAL
    astar = with_open_f(astar_grid(grid, s, z, "manhattan", 4), lambda n: manhattan(n, z))
    dijk = with_open_f(astar_grid(grid, s, z, "zero", 4), lambda n: 0.0)
    lines = ["\\begin{tikzpicture}[scale=0.85]"]
    lines += panel(grid, astar, s, z, 0.0,
                   "(a) \\astar, Manhattan $\\hcost$: %d expansions" % astar.num_expansions)
    lines += panel(grid, dijk, s, z, 8.0,
                   "(b) Dijkstra ($\\hcost = 0$): %d expansions" % dijk.num_expansions)
    lines.append("\\end{tikzpicture}")
    write("example.tex", lines)
    return astar, dijk


def tiebreak_figure():
    n = 20
    grid = np.zeros((n, n), dtype=int)
    s, z = (0, 0), (n - 1, n - 1)
    high = astar_grid(grid, s, z, "manhattan", 4, tie_break="high_g")
    low = astar_grid(grid, s, z, "manhattan", 4, tie_break="low_g")
    lines = ["\\begin{tikzpicture}[scale=0.27]"]
    lines += panel(grid, high, s, z, 0.0,
                   "(a) larger $\\gcost$ first: %d expansions" % high.num_expansions,
                   labels=False)
    lines += panel(grid, low, s, z, 25.0,
                   "(b) smaller $\\gcost$ first: %d expansions" % low.num_expansions,
                   labels=False)
    lines.append("\\end{tikzpicture}")
    write("tiebreak.tex", lines)
    return high, low


if __name__ == "__main__":
    a, d = example_figure()
    print("worked example: A* %d expansions, Dijkstra %d, cost %g"
          % (a.num_expansions, d.num_expansions, a.cost))
    h, l = tiebreak_figure()
    print("tie-breaking on the empty 20x20 grid: larger g first %d, smaller g first %d"
          % (h.num_expansions, l.num_expansions))
