"""Draw the worked example of Chapter 6: three ARA* iterations on one grid.

Writes figures/ch06/example.tex, a single tikzpicture with three panels
(eps = 3, 2, 1).  Each panel shows the cells expanded in that iteration
(grey), the cells in OPEN when ImprovePath stopped (blue), the cells that
were moved to INCONS (orange hatching), the published path (solid blue)
and, dashed, the path of the previous iteration.  The trace of every
expansion is printed as LaTeX table rows for the chapter's trace table.

Run from Overleaf/:   python3 code/figures/gen_ch06_example.py
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from ch06_arastar import (ARAStar, EXAMPLE_GOAL, EXAMPLE_SCHEDULE,  # noqa: E402
                          EXAMPLE_START, example_grid)

OUT = os.path.join(os.path.dirname(HERE), "..", "figures", "ch06", "example.tex")
SCALE = 0.56
GAP = 0.9            # gap between the panels in grid units
HATCH = r"\fill[pattern=north east lines,pattern color=sbOrange!70] (%d,%d) rectangle ++(1,1);"


def cell(c):
    return "(%d,%d)" % c


def fmt(x):
    return "%.2f" % x


def panel(lines, grid, sol, prev_path, shift):
    w, h = grid.width, grid.height
    lines.append(r"\begin{scope}[xshift=%.2fcm]" % shift)
    for (x, y) in sorted(sol.closed):
        lines.append(r"\fill[sbclosed] (%d,%d) rectangle ++(1,1);" % (x, y))
    for (x, y) in sorted(sol.open):
        lines.append(r"\fill[sbopen] (%d,%d) rectangle ++(1,1);" % (x, y))
    for (x, y) in sorted(sol.incons):
        lines.append(HATCH % (x, y))
    for (x, y) in sorted(grid.obstacles):
        lines.append(r"\fill[sbobstacle] (%d,%d) rectangle ++(1,1);" % (x, y))
    lines.append(r"\draw[black!40,very thin] (0,0) grid (%d,%d);" % (w, h))
    for x in range(w):
        lines.append(r"\node[font=\tiny,text=sbGray] at (%.1f,-0.25) {%d};" % (x + 0.5, x))
    for y in range(h):
        lines.append(r"\node[font=\tiny,text=sbGray] at (-0.25,%.1f) {%d};" % (y + 0.5, y))
    if prev_path is not None:
        pts = " -- ".join("(%.1f,%.1f)" % (x + 0.5, y + 0.5) for x, y in prev_path)
        lines.append(r"\draw[sbpathalt,line width=1.1pt] %s;" % pts)
    pts = " -- ".join("(%.1f,%.1f)" % (x + 0.5, y + 0.5) for x, y in sol.path)
    lines.append(r"\draw[sbpath] %s;" % pts)
    sx, sy = sol.path[0]
    gx, gy = sol.path[-1]
    lines.append(r"\node[sbstart,font=\tiny] at (%.1f,%.1f) {S};" % (sx + 0.5, sy + 0.5))
    lines.append(r"\node[sbgoal,font=\tiny] at (%.1f,%.1f) {G};" % (gx + 0.5, gy + 0.5))
    lines.append(r"\node[sbannot,anchor=north,align=center,text=black] at (%.1f,-0.55) "
                 r"{$\eps=%g$: cost $%.2f$, $\eps'=%.2f$\\ %d expansions};"
                 % (w / 2, sol.eps, sol.cost, sol.eps_bound, sol.expansions))
    lines.append(r"\end{scope}")


def main():
    grid = example_grid()
    ara = ARAStar(grid, EXAMPLE_START, EXAMPLE_GOAL, EXAMPLE_SCHEDULE, trace=True)
    sols = list(ara.run())
    lines = ["% Generated by code/figures/gen_ch06_example.py -- do not edit",
             r"\begin{tikzpicture}[scale=%.2f]" % SCALE]
    prev = None
    for i, sol in enumerate(sols):
        panel(lines, grid, sol, prev, i * (grid.width + GAP) * SCALE)
        prev = sol.path
    # legend below the panels
    y0 = -1.75
    x0 = 0.0
    items = [(r"\fill[sbclosed]", "expanded (\\Closed)"),
             (r"\fill[sbopen]", "in \\Open at the end"),
             (r"\fill[pattern=north east lines,pattern color=sbOrange!70]", "moved to \\textsc{Incons}"),
             (r"\fill[sbobstacle]", "obstacle")]
    x = x0
    for fill, text in items:
        lines.append(r"%s (%.2f,%.2f) rectangle ++(0.6,0.6);" % (fill, x, y0))
        lines.append(r"\draw[black!40,very thin] (%.2f,%.2f) rectangle ++(0.6,0.6);" % (x, y0))
        lines.append(r"\node[sbannot,anchor=west] at (%.2f,%.2f) {%s};" % (x + 0.7, y0 + 0.3, text))
        x += 6.2
    lines.append(r"\draw[sbpathalt,line width=1.1pt] (%.2f,%.2f) -- ++(1.0,0);" % (x, y0 + 0.3))
    lines.append(r"\node[sbannot,anchor=west] at (%.2f,%.2f) {previous path};" % (x + 1.1, y0 + 0.3))
    lines.append(r"\end{tikzpicture}")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(OUT))

    # summary and LaTeX trace rows for the chapter
    for sol in sols:
        print("iteration %d eps=%g cost=%.4f g_goal=%.4f L=%.4f eps'=%.4f exp=%d total=%d"
              % (sol.iteration, sol.eps, sol.cost, sol.g_goal, sol.lower_bound,
                 sol.eps_bound, sol.expansions, sol.total_expansions))
        print("   path:", " ".join(cell(c) for c in sol.path))
        print("   incons:", sorted(sol.incons))
    print("\n%% trace rows: step & s & g & h & f & improved successors & min f in OPEN")
    for ev in ara.trace:
        if ev["event"] == "start":
            print(r"\midrule" + "\n" + r"\multicolumn{7}{@{}l}{\emph{Iteration %d, $\eps=%g$; \Open holds %d states}}\\"
                  % (ev["iteration"], ev["eps"], len(ev["open"])))
            continue
        succ = ", ".join("%s\\,%s%s" % (cell(t), fmt(g), "$^{\\mathrm{I}}$" if w == "INCONS" else "")
                         for t, g, w in ev["lowered"]) or "--"
        minf = fmt(ev["min_open_f"]) if ev["min_open_f"] != float("inf") else r"$\infty$"
        print(r"%d & %s & %s & %s & %s & %s & %s\\" % (
            ev["step"], cell(ev["state"]), fmt(ev["g"]), fmt(ev["h"]), fmt(ev["f"]), succ, minf))


if __name__ == "__main__":
    main()
