"""Generate the algorithm-output figures and data of chapter 17.

Everything comes from code/ch17_rrt_star.py with fixed seeds.  Written:

    figures/ch17/snapshots.tex        RRT* on the map of chapter 16 after
                                      200, 1000 and 3000 iterations with the
                                      current best path (seed 1)
    figures/ch17/ellipses.tex         the informed set shrinking as c_best
                                      improves (wide field, seed 1), with
                                      the last informed samples
    figures/data/ch17-convergence.dat mean best cost against iterations for
                                      RRT, RRT* and Informed RRT* over
                                      N_SEEDS seeds on the two maps
                                      (columns: iters, rrt_map, star_map,
                                      informed_map, rrt_wide, star_wide,
                                      informed_wide; nan while some seed has
                                      no solution yet)

The numbers quoted in the chapter are printed at the end.
Run from Overleaf/:   python3 code/figures/gen_ch17_convergence.py
"""
import math
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from ch17_rrt_star import (rrt_star, rrt_plain, path_length,  # noqa: E402
                           worked_example_world, wide_example_world,
                           visibility_shortest_path, grid_astar_reference,
                           gamma_star, free_volume)

ROOT = os.path.dirname(os.path.dirname(HERE))          # Overleaf/
FIGDIR = os.path.join(ROOT, "figures", "ch17")
DATDIR = os.path.join(ROOT, "figures", "data")
START, GOAL = np.array([1.0, 1.0]), np.array([9.0, 9.0])
ETA, P_GOAL = 1.0, 0.05
GAMMA_MAP, GAMMA_WIDE = 13.3, 45.0
SEED, N_SEEDS, MAX_ITERS = 1, 20, 3000


def f(x):
    return "%.3f" % x


def write(name, lines):
    path = os.path.join(FIGDIR, name)
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", os.path.relpath(path, ROOT))


def draw_edges(V, parent, n, style, tr, chunk=12):
    out, edges = [], [(int(parent[i]), i) for i in range(1, n)]
    for k in range(0, len(edges), chunk):
        parts = []
        for (i, j) in edges[k:k + chunk]:
            a, b = tr(V[i]), tr(V[j])
            parts.append("(%s,%s)--(%s,%s)" % (f(a[0]), f(a[1]), f(b[0]), f(b[1])))
        out.append("\\draw[%s] %s;" % (style, " ".join(parts)))
    return out


def draw_path(path, style, tr):
    pts = ["(%s,%s)" % (f(p[0]), f(p[1])) for p in map(tr, path)]
    out = []
    for k in range(0, len(pts), 8):
        out.append(("\\draw[%s] " % style if k == 0 else "  ")
                   + "--".join(pts[k:k + 8]) + ("--" if k + 8 < len(pts) else ";"))
    return out


def map_2d(world, tr):
    lo, hi = tr(world.lower), tr(world.upper)
    out = ["\\draw[black!50,very thin] (%s,%s) rectangle (%s,%s);"
           % (f(lo[0]), f(lo[1]), f(hi[0]), f(hi[1]))]
    for blo, bhi in zip(world.box_lo, world.box_hi):
        a, b = tr(blo), tr(bhi)
        out.append("\\fill[sbobstacle] (%s,%s) rectangle (%s,%s);"
                   % (f(a[0]), f(a[1]), f(b[0]), f(b[1])))
    return out


def markers(tr):
    s, g = tr(START), tr(GOAL)
    return ["\\node[sbstart] at (%s,%s) {};" % (f(s[0]), f(s[1])),
            "\\node[sbgoal] at (%s,%s) {};" % (f(g[0]), f(g[1]))]


# ----------------------------------------------------------------------
def snapshots_figure(world):
    its = (200, 1000, 3000)
    res = rrt_star(world, START, GOAL, eta=ETA, gamma=GAMMA_MAP, p_goal=P_GOAL,
                   max_iters=MAX_ITERS, seed=SEED, snapshots=its)
    scale, gap = 0.42, 0.6
    lines = ["% RRT* on the map of chapter 16 after 200, 1000 and 3000",
             "%% iterations (seed %d, eta %.1f, gamma %.1f, goal bias %.2f);"
             % (SEED, ETA, GAMMA_MAP, P_GOAL),
             "% generated by code/figures/gen_ch17_convergence.py -- do not edit.",
             "\\begin{tikzpicture}"]
    for panel, it in enumerate(its):
        x0 = panel * (10 * scale + gap)
        tr = (lambda q, x0=x0: (x0 + q[0] * scale, q[1] * scale))
        n, path, parent = res.snapshots[it]
        lines += map_2d(world, tr)
        lines += draw_edges(res.tree.V, parent, n, "sbBlue!60,line width=0.3pt", tr)
        if path is not None:
            lines += draw_path(path, "sbpath", tr)
        lines += markers(tr)
        c = res.history[it - 1, 3]
        label = "(%s) $%d$ iterations\\\\$%d$ vertices, %s" % (
            "abc"[panel], it, n, "no path yet" if not np.isfinite(c) else "cost $%.2f$" % c)
        lines.append("\\node[sbannot,align=center] at (%s,%s) {%s};"
                     % (f(x0 + 5 * scale), f(-0.55), label))
    lines.append("\\end{tikzpicture}")
    write("snapshots.tex", lines)
    return res


def ellipses_figure(wide):
    its = (1000, 2000, 3000)
    res = rrt_star(wide, START, GOAL, eta=ETA, gamma=GAMMA_WIDE, p_goal=P_GOAL,
                   max_iters=MAX_ITERS, seed=SEED, informed=True, snapshots=its)
    first_it = res.solution_iter
    values = [(first_it, res.history[first_it - 1, 3])]
    values += [(it, res.history[it - 1, 3]) for it in its]
    scale = 0.2
    tr = (lambda q: ((q[0] + 10) * scale, (q[1] + 10) * scale))
    s = res.sampler
    lines = ["% The informed set of the wide field shrinking as c_best improves",
             "%% (Informed RRT*, seed %d), with 200 samples drawn from the" % SEED,
             "% final set; generated by code/figures/gen_ch17_convergence.py.",
             "\\begin{tikzpicture}"]
    lines += map_2d(wide, tr)
    cx, cy = tr(s.centre)
    angle = math.degrees(math.atan2(GOAL[1] - START[1], GOAL[0] - START[0]))
    styles = ["sbOrange,dashed,thick", "sbOrange!80,thick", "sbPurple,thick",
              "sbPurple!80!black,very thick"]
    rng = np.random.default_rng(5)
    pts = [s.sample(rng, res.cost, wide) for _ in range(200)]
    for p in pts:
        a = tr(p)
        lines.append("\\fill[sbBlue!70] (%s,%s) circle (0.6pt);" % (f(a[0]), f(a[1])))
    for k, (it, c) in enumerate(values):
        a, b = s.semi_axes(c) * scale
        lines.append("\\draw[%s,rotate around={%s:(%s,%s)}] (%s,%s) ellipse (%s and %s);"
                     % (styles[k], f(angle), f(cx), f(cy), f(cx), f(cy), f(a), f(b)))
        # label at the far end of the transverse axis
        lx = cx + (a + 0.35) * math.cos(math.radians(angle)) * (1 if k % 2 == 0 else -1)
        ly = cy + (a + 0.35) * math.sin(math.radians(angle)) * (1 if k % 2 == 0 else -1)
        lines.append("\\node[sbannot,text=%s] at (%s,%s) {$c=%.1f$};"
                     % (styles[k].split(",")[0], f(lx), f(ly), c))
    lines += draw_path(res.path, "sbpath", tr)
    lines += markers(tr)
    lines.append("\\end{tikzpicture}")
    write("ellipses.tex", lines)
    print("ellipses (wide field, seed %d): first solution at iteration %d, "
          "c_best %s" % (SEED, first_it,
                         ", ".join("%d: %.3f" % (it, c) for it, c in values)))
    print("   informed set: %.1f%% of X at the first solution, %.1f%% at the "
          "end; %d of %d draws rejected"
          % (100 * s.measure(values[0][1]) / wide.volume(),
             100 * s.measure(res.cost) / wide.volume(), s.rejections, s.draws))
    return res


# ----------------------------------------------------------------------
def convergence(world, wide):
    grid = np.arange(0, MAX_ITERS + 1, 25)
    grid[0] = 1
    configs = [("rrt_map", world, GAMMA_MAP, rrt_plain, False),
               ("star_map", world, GAMMA_MAP, rrt_star, False),
               ("informed_map", world, GAMMA_MAP, rrt_star, True),
               ("rrt_wide", wide, GAMMA_WIDE, rrt_plain, False),
               ("star_wide", wide, GAMMA_WIDE, rrt_star, False),
               ("informed_wide", wide, GAMMA_WIDE, rrt_star, True)]
    columns, summary = {}, {}
    for name, w, gamma, planner, informed in configs:
        costs = np.full((N_SEEDS, MAX_ITERS), np.inf)
        first, finals, checks = [], [], []
        for s in range(N_SEEDS):
            kw = dict(eta=ETA, p_goal=P_GOAL, max_iters=MAX_ITERS, seed=s)
            if planner is rrt_star:
                kw.update(gamma=gamma, informed=informed)
            r = planner(w, START, GOAL, **kw)
            costs[s] = r.history[:, 3]
            first.append(r.solution_iter if r.solution_iter else np.inf)
            finals.append(r.cost)
            checks.append(r.segment_checks)
        col = []
        for g in grid:
            c = costs[:, g - 1]
            col.append(c.mean() if np.all(np.isfinite(c)) else np.nan)
        columns[name] = col
        first = np.array(first, dtype=float)
        finals = np.array(finals)
        summary[name] = dict(
            first_median=np.median(first[np.isfinite(first)]),
            first_max=np.max(first), solved=np.isfinite(finals).mean(),
            final_mean=finals[np.isfinite(finals)].mean(),
            final_sd=finals[np.isfinite(finals)].std(),
            final_min=finals[np.isfinite(finals)].min(),
            final_max=finals[np.isfinite(finals)].max(),
            at1000=np.nanmean(np.where(np.isfinite(costs[:, 999]),
                                       costs[:, 999], np.nan)),
            checks=np.mean(checks))
    path = os.path.join(DATDIR, "ch17-convergence.dat")
    with open(path, "w") as fh:
        fh.write("iters " + " ".join(c[0] for c in configs) + "\n")
        for k, g in enumerate(grid):
            fh.write("%d " % g + " ".join(
                "nan" if np.isnan(columns[c[0]][k]) else "%.3f" % columns[c[0]][k]
                for c in configs) + "\n")
    print("wrote", os.path.relpath(path, ROOT))
    for name, _, _, _, _ in configs:
        s = summary[name]
        print("%-14s solved %.2f  first solution median %4.0f (max %4.0f)  "
              "cost at 1000: %.2f  final %.2f +- %.2f (min %.2f, max %.2f)  "
              "segment checks %.0f" % (
                  name, s["solved"], s["first_median"], s["first_max"],
                  s["at1000"], s["final_mean"], s["final_sd"], s["final_min"],
                  s["final_max"], s["checks"]))


# ----------------------------------------------------------------------
if __name__ == "__main__":
    os.makedirs(FIGDIR, exist_ok=True)
    os.makedirs(DATDIR, exist_ok=True)
    world, wide = worked_example_world(), wide_example_world()
    for name, w in (("map", world), ("wide", wide)):
        vis, vis_len = visibility_shortest_path(w, START, GOAL)
        mu = free_volume(w)
        print("%s: mu(X_free) ~ %.1f, gamma* = %.2f, optimum %.3f via %s"
              % (name, mu, gamma_star(2, mu), vis_len,
                 "; ".join("(%.2f, %.2f)" % (p[0], p[1]) for p in vis)))
    taut, taut_len, grid_len = grid_astar_reference(world, START, GOAL, 0.1)
    print("map: grid A* (h = 0.1, 8-connected) %.3f, after string pulling %.3f"
          % (grid_len, taut_len))
    res = snapshots_figure(world)
    print("worked example (seed %d): first solution at iteration %d, cost %.3f;"
          " final %d vertices, cost %.3f, %d segment checks, mean |Near| %.1f"
          % (SEED, res.solution_iter, res.history[res.solution_iter - 1, 3],
             res.tree.n, res.cost, res.segment_checks, res.near_sizes))
    print("table rows (iteration & |V| & r_n & c_best):")
    for it in (200, 351, 500, 1000, 1500, 2000, 3000):
        row = res.history[it - 1]
        print("  %d & %d & %.3f & %s \\\\" % (
            it, row[1], row[2], "--" if not np.isfinite(row[3]) else "%.3f" % row[3]))
    ellipses_figure(wide)
    convergence(world, wide)
