"""Generate the figures of chapter 16 (RRT) as TikZ files and one data file.

Everything comes from code/ch16_rrt.py with fixed seeds.  Written files:

    figures/ch16/tree-snapshots.tex   the worked-example tree after 50, 200
                                      and 1000 iterations, with the path
    figures/ch16/voronoi.tex          a small tree and the Voronoi regions
                                      of its vertices (Voronoi bias)
    figures/ch16/jagged.tex           the longest RRT path of 100 runs
                                      against the visibility-graph shortest
                                      path (RRT is not optimal)
    figures/ch16/connect.tex          the two trees of RRT-Connect
    figures/ch16/shortcut.tex         raw path, shortcut result, pruning
    figures/ch16/scene3d.tex          the 3D box field in an oblique
                                      projection with the RRT path
    figures/data/ch16-iterations.dat  fraction of 100 runs solved within a
                                      budget of iterations, for RRT with
                                      goal bias 0, 0.05 and 0.5 and for
                                      RRT-Connect (columns iters, rrt_p00,
                                      rrt_p05, rrt_p50, connect)

The statistics quoted in the chapter text are printed at the end.
Run from Overleaf/:   python3 code/figures/gen_ch16_tree.py
"""
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from ch16_rrt import (World, rrt, rrt_connect, shortcut, prune,  # noqa: E402
                      path_length, visibility_shortest_path,
                      worked_example_world, scene_3d)

ROOT = os.path.dirname(os.path.dirname(HERE))          # Overleaf/
FIGDIR = os.path.join(ROOT, "figures", "ch16")
DATDIR = os.path.join(ROOT, "figures", "data")
START, GOAL = np.array([1.0, 1.0]), np.array([9.0, 9.0])
ETA, P_GOAL, R_GOAL = 0.5, 0.05, 0.5
SEED = 1                 # the worked example
N_SEEDS = 100            # for the statistics
MAX_ITERS = 3000


def f(x):
    return "%.3f" % x


def write(name, lines):
    path = os.path.join(FIGDIR, name)
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", os.path.relpath(path, ROOT))


def draw_edges(tree, style, transform, chunk=12):
    """One \\draw with many sub-paths per `chunk` edges."""
    out = []
    edges = tree.edges()
    for k in range(0, len(edges), chunk):
        parts = []
        for (i, j) in edges[k:k + chunk]:
            a, b = transform(tree.V[i]), transform(tree.V[j])
            parts.append("(%s,%s)--(%s,%s)" % (f(a[0]), f(a[1]), f(b[0]), f(b[1])))
        out.append("\\draw[%s] %s;" % (style, " ".join(parts)))
    return out


def draw_path(path, style, transform):
    pts = ["(%s,%s)" % (f(p[0]), f(p[1])) for p in map(transform, path)]
    out = []
    for k in range(0, len(pts), 8):
        out.append(("\\draw[%s] " % style if k == 0 else "  ")
                   + "--".join(pts[k:k + 8]) + ("--" if k + 8 < len(pts) else ";"))
    return out


def map_2d(world, transform, scale):
    """Border and box obstacles of a 2D world."""
    lo, hi = transform(world.lower), transform(world.upper)
    out = ["\\draw[black!50,very thin] (%s,%s) rectangle (%s,%s);"
           % (f(lo[0]), f(lo[1]), f(hi[0]), f(hi[1]))]
    for blo, bhi in zip(world.box_lo, world.box_hi):
        a, b = transform(blo), transform(bhi)
        out.append("\\fill[sbobstacle] (%s,%s) rectangle (%s,%s);"
                   % (f(a[0]), f(a[1]), f(b[0]), f(b[1])))
    return out


def markers(transform, scale, start=START, goal=GOAL, r_goal=R_GOAL):
    s, g = transform(start), transform(goal)
    return ["\\draw[sbGoal,dashed,thin] (%s,%s) circle (%s);"
            % (f(g[0]), f(g[1]), f(r_goal * scale)),
            "\\node[sbstart] at (%s,%s) {};" % (f(s[0]), f(s[1])),
            "\\node[sbgoal] at (%s,%s) {};" % (f(g[0]), f(g[1]))]


# ----------------------------------------------------------------------
def tree_snapshots(world):
    scale, gap = 0.42, 0.6
    res = rrt(world, START, GOAL, eta=ETA, p_goal=P_GOAL, r_goal=R_GOAL,
              max_iters=1000, seed=SEED, stop_at_goal=False,
              snapshots=(50, 200, 1000))
    lines = ["% The worked-example tree after 50, 200 and 1000 iterations",
             "%% (seed %d, eta %.1f, goal bias %.2f); generated by"
             % (SEED, ETA, P_GOAL),
             "% code/figures/gen_ch16_tree.py -- do not edit.",
             "\\begin{tikzpicture}"]
    for panel, it in enumerate((50, 200, 1000)):
        x0 = panel * (10 * scale + gap)
        tr = (lambda q, x0=x0: (x0 + q[0] * scale, q[1] * scale))
        n = res.snapshots[it]
        sub = type("T", (), {})()      # the tree truncated to n vertices
        sub.V, sub.parent, sub.n = res.tree.V, res.tree.parent, n
        sub.edges = lambda n=n, t=res.tree: [(int(t.parent[i]), i)
                                             for i in range(1, n)]
        lines += map_2d(world, tr, scale)
        lines += draw_edges(sub, "sbBlue!70,line width=0.35pt", tr)
        if it >= res.solution_iter:
            lines += draw_path(res.path, "sbpath", tr)
        lines += markers(tr, scale)
        label = "(%s) %d iterations, %d vertices" % ("abc"[panel], it, n)
        lines.append("\\node[sbannot] at (%s,%s) {%s};"
                     % (f(x0 + 5 * scale), f(-0.4), label))
    lines.append("\\end{tikzpicture}")
    write("tree-snapshots.tex", lines)
    return res


# ----------------------------------------------------------------------
def clip_polygon(poly, m, nrm):
    """Sutherland-Hodgman: keep the part of poly with (x - m) . nrm <= 0."""
    out = []
    for k in range(len(poly)):
        p, q = poly[k - 1], poly[k]
        fp, fq = float((p - m) @ nrm), float((q - m) @ nrm)
        if fq <= 0:
            if fp > 0:
                out.append(p + (fp / (fp - fq)) * (q - p))
            out.append(q)
        elif fp <= 0:
            out.append(p + (fp / (fp - fq)) * (q - p))
    return out


def polygon_area(poly):
    x = np.array([p[0] for p in poly])
    y = np.array([p[1] for p in poly])
    return 0.5 * abs(float(np.dot(x, np.roll(y, -1)) - np.dot(y, np.roll(x, -1))))


def voronoi_figure():
    world = World([0, 0], [10, 10])
    eta = 1.0
    res = rrt(world, np.array([2.0, 2.0]), np.array([99.0, 99.0]), eta=eta,
              p_goal=0.0, max_iters=14, seed=7)
    tree = res.tree
    V = tree.V[:tree.n]
    square = [np.array(c, dtype=float)
              for c in ((0, 0), (10, 0), (10, 10), (0, 10))]
    cells, areas = [], []
    for i in range(len(V)):
        poly = square
        for j in range(len(V)):
            if j != i:
                poly = clip_polygon(poly, 0.5 * (V[i] + V[j]), V[j] - V[i])
        cells.append(poly)
        areas.append(polygon_area(poly))
    big = int(np.argmax(areas))
    # a sample in the largest region and the extension it causes
    rng = np.random.default_rng(3)
    while True:
        q = world.sample(rng)
        if tree.nearest(q) == big and np.linalg.norm(q - V[big]) > 2.5:
            break
    direction = (q - V[big]) / np.linalg.norm(q - V[big])
    q_new = V[big] + eta * direction
    scale = 0.55
    tr = (lambda p: (p[0] * scale, p[1] * scale))
    lines = ["% A 15-vertex RRT in an empty square and the Voronoi regions of",
             "% its vertices; generated by code/figures/gen_ch16_tree.py.",
             "\\begin{tikzpicture}"]
    for i, poly in enumerate(cells):
        fill = "sbOrange!25" if i == big else "sbBlue!%d" % (6 + 10 * (i % 2))
        pts = "--".join("(%s,%s)" % (f(a), f(b)) for a, b in map(tr, poly))
        lines.append("\\draw[fill=%s,draw=sbBlue!50,very thin] %s--cycle;"
                     % (fill, pts))
    lines += draw_edges(tree, "sbedge", tr)
    for i, v in enumerate(V):
        a = tr(v)
        lines.append("\\fill[sbBlue] (%s,%s) circle (1.6pt);" % (f(a[0]), f(a[1])))
    s = tr(V[0])
    lines.append("\\node[sbstart] at (%s,%s) {};" % (f(s[0]), f(s[1])))
    a, b, c = tr(V[big]), tr(q), tr(q_new)
    lines.append("\\draw[sbannot,dashed,-{Stealth[length=4pt]}] (%s,%s) -- (%s,%s);"
                 % (f(a[0]), f(a[1]), f(b[0]), f(b[1])))
    lines.append("\\fill[sbRed] (%s,%s) circle (1.8pt);" % (f(b[0]), f(b[1])))
    lines.append("\\node[sbannot,anchor=west] at (%s,%s) {$q_{\\mathrm{rand}}$};"
                 % (f(b[0] + 0.1), f(b[1])))
    lines.append("\\draw[sbOrange,line width=1.4pt] (%s,%s) -- (%s,%s);"
                 % (f(a[0]), f(a[1]), f(c[0]), f(c[1])))
    lines.append("\\fill[sbOrange] (%s,%s) circle (1.8pt);" % (f(c[0]), f(c[1])))
    lines.append("\\node[sbannot,anchor=north west] at (%s,%s) {$q_{\\mathrm{new}}$};"
                 % (f(c[0] + 0.05), f(c[1] - 0.05)))
    lines.append("\\node[sbannot,anchor=south east] at (%s,%s) {$q_{\\mathrm{near}}$};"
                 % (f(a[0] - 0.05), f(a[1] + 0.05)))
    lines.append("\\end{tikzpicture}")
    write("voronoi.tex", lines)
    order = np.argsort(areas)[::-1]
    print("voronoi: %d vertices; largest region %.1f%% of the area, "
          "three largest %.1f%%, smallest %.1f%%, uniform share %.1f%%"
          % (len(V), 100 * areas[big] / 100.0,
             100 * sum(areas[k] for k in order[:3]) / 100.0,
             100 * min(areas) / 100.0, 100.0 / len(V)))


# ----------------------------------------------------------------------
def statistics(world):
    """Iterations to solution over N_SEEDS seeds for four planners."""
    grid = np.arange(0, MAX_ITERS + 1, 25)
    configs = [("rrt_p00", lambda s: rrt(world, START, GOAL, eta=ETA, p_goal=0.0,
                                         r_goal=R_GOAL, max_iters=MAX_ITERS, seed=s)),
               ("rrt_p05", lambda s: rrt(world, START, GOAL, eta=ETA, p_goal=0.05,
                                         r_goal=R_GOAL, max_iters=MAX_ITERS, seed=s)),
               ("rrt_p50", lambda s: rrt(world, START, GOAL, eta=ETA, p_goal=0.5,
                                         r_goal=R_GOAL, max_iters=MAX_ITERS, seed=s)),
               ("connect", lambda s: rrt_connect(world, START, GOAL, eta=ETA,
                                                 max_iters=MAX_ITERS, seed=s))]
    columns, summary, worst = {}, {}, None
    for name, planner in configs:
        iters, verts, lens = [], [], []
        for s in range(N_SEEDS):
            r = planner(s)
            iters.append(r.solution_iter if r.solution_iter else np.inf)
            verts.append(r.n_vertices)
            if r.path is not None:
                lens.append(path_length(r.path))
                if name == "rrt_p05" and (worst is None or lens[-1] > worst[1]):
                    worst = (s, lens[-1])
        iters = np.array(iters, dtype=float)
        columns[name] = [(iters <= g).mean() for g in grid]
        solved = np.isfinite(iters)
        summary[name] = dict(success=solved.mean(),
                             median=np.median(iters[solved]),
                             mean=iters[solved].mean(),
                             vertices=np.mean(verts),
                             length=np.mean(lens), length_sd=np.std(lens),
                             length_min=np.min(lens), length_max=np.max(lens))
    path = os.path.join(DATDIR, "ch16-iterations.dat")
    with open(path, "w") as fh:
        fh.write("iters " + " ".join(c for c, _ in configs) + "\n")
        for k, g in enumerate(grid):
            fh.write("%d " % g + " ".join("%.3f" % columns[c][k]
                                          for c, _ in configs) + "\n")
    print("wrote", os.path.relpath(path, ROOT))
    for name, _ in configs:
        s = summary[name]
        print("%-8s success %.2f  iterations median %.0f mean %.0f  "
              "vertices %.0f  length %.2f +- %.2f (min %.2f, max %.2f)"
              % (name, s["success"], s["median"], s["mean"], s["vertices"],
                 s["length"], s["length_sd"], s["length_min"], s["length_max"]))
    return worst


# ----------------------------------------------------------------------
def jagged_figure(world, worst_seed):
    res = rrt(world, START, GOAL, eta=ETA, p_goal=P_GOAL, r_goal=R_GOAL,
              max_iters=MAX_ITERS, seed=worst_seed)
    ref, ref_len = visibility_shortest_path(world, START, GOAL)
    scale = 0.5
    tr = (lambda q: (q[0] * scale, q[1] * scale))
    lines = ["%% The longest of 100 RRT paths (seed %d) against the shortest"
             % worst_seed,
             "% path; generated by code/figures/gen_ch16_tree.py.",
             "\\begin{tikzpicture}"]
    lines += map_2d(world, tr, scale)
    lines += draw_edges(res.tree, "sbBlue!30,line width=0.3pt", tr)
    lines += draw_path(ref, "sbpathalt", tr)
    lines += draw_path(res.path, "sbpath", tr)
    lines += markers(tr, scale)
    lines.append("\\end{tikzpicture}")
    write("jagged.tex", lines)
    print("jagged: seed %d, RRT path %.2f, shortest %.2f, ratio %.2f, "
          "solution at iteration %d" % (worst_seed, path_length(res.path),
                                        ref_len, path_length(res.path) / ref_len,
                                        res.solution_iter))


def connect_figure(world):
    res = rrt_connect(world, START, GOAL, eta=ETA, max_iters=MAX_ITERS, seed=SEED)
    scale = 0.5
    tr = (lambda q: (q[0] * scale, q[1] * scale))
    lines = ["%% RRT-Connect on the worked-example map (seed %d); generated by"
             % SEED, "% code/figures/gen_ch16_tree.py.", "\\begin{tikzpicture}"]
    lines += map_2d(world, tr, scale)
    lines += draw_edges(res.tree, "sbBlue!70,line width=0.35pt", tr)
    lines += draw_edges(res.tree_goal, "sbOrange!80,line width=0.35pt", tr)
    lines += draw_path(res.path, "sbpath", tr)
    lines += markers(tr, scale)
    lines.append("\\end{tikzpicture}")
    write("connect.tex", lines)
    print("connect: seed %d solved at iteration %d with %d + %d vertices, "
          "length %.2f" % (SEED, res.iterations, res.tree.n, res.tree_goal.n,
                           path_length(res.path)))


def shortcut_figure(world, res):
    raw = res.path
    sc = shortcut(raw, world, n_tries=100, seed=0)
    pr = prune(raw, world)
    scale = 0.5
    tr = (lambda q: (q[0] * scale, q[1] * scale))
    lines = ["% Raw RRT path of the worked example, after random shortcutting",
             "% and after greedy pruning; generated by",
             "% code/figures/gen_ch16_tree.py.", "\\begin{tikzpicture}"]
    lines += map_2d(world, tr, scale)
    lines += draw_path(raw, "black!45,line width=0.8pt", tr)
    lines += draw_path(sc, "sbpath", tr)
    lines += draw_path(pr, "sbpathalt", tr)
    for p in pr:
        a = tr(p)
        lines.append("\\fill[sbOrange] (%s,%s) circle (1.5pt);" % (f(a[0]), f(a[1])))
    lines += markers(tr, scale)
    lines.append("\\end{tikzpicture}")
    write("shortcut.tex", lines)
    print("shortcut: raw %.2f (%d vertices), shortcut %.2f (%d), prune %.2f (%d)"
          % (path_length(raw), len(raw), path_length(sc), len(sc),
             path_length(pr), len(pr)))


# ----------------------------------------------------------------------
def scene3d_figure():
    world = scene_3d()
    s3, g3 = np.array([0.5, 0.5, 0.5]), np.array([9.5, 9.5, 9.5])
    res = rrt(world, s3, g3, eta=0.8, p_goal=0.05, r_goal=0.5, max_iters=4000,
              seed=3)
    sc = shortcut(res.path, world, n_tries=100, seed=0)
    scale = 0.5
    ey = np.array([0.5, 0.42])

    def tr(p):
        return ((p[0] + ey[0] * p[1]) * scale, (p[2] + ey[1] * p[1]) * scale)

    def poly(corners):
        return "--".join("(%s,%s)" % (f(a), f(b)) for a, b in map(tr, corners)) + "--cycle"

    lines = ["% The 3D box field in an oblique projection with the RRT tree,",
             "% the raw path and the shortcut path; generated by",
             "% code/figures/gen_ch16_tree.py.", "\\begin{tikzpicture}"]
    # floor, back walls and axes
    lines.append("\\draw[fill=black!4,draw=black!50,very thin] %s;"
                 % poly([(0, 0, 0), (10, 0, 0), (10, 10, 0), (0, 10, 0)]))
    for k in range(1, 10):
        lines.append("\\draw[black!15,very thin] %s -- %s %s -- %s;" % (
            "(%s,%s)" % tuple(map(f, tr((k, 0, 0)))), "(%s,%s)" % tuple(map(f, tr((k, 10, 0)))),
            "(%s,%s)" % tuple(map(f, tr((0, k, 0)))), "(%s,%s)" % tuple(map(f, tr((10, k, 0))))))
    lines.append("\\draw[black!50,very thin] %s;" % poly([(0, 10, 0), (10, 10, 0), (10, 10, 10), (0, 10, 10)]))
    lines.append("\\draw[black!50,very thin] %s;" % poly([(0, 0, 0), (0, 10, 0), (0, 10, 10), (0, 0, 10)]))
    for lab, p in (("$x$", (10.6, 0, 0)), ("$y$", (10, 10.8, 0)), ("$z$", (0, 0, 10.6))):
        a = tr(p)
        lines.append("\\node[sbannot] at (%s,%s) {%s};" % (f(a[0]), f(a[1]), lab))
    # boxes, far ones first
    order = sorted(range(len(world.box_lo)), key=lambda i: (-world.box_lo[i][1], world.box_lo[i][0]))
    for i in order:
        (x0, y0, z0), (x1, y1, z1) = world.box_lo[i], world.box_hi[i]
        faces = [([(x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1)], 45),   # front
                 ([(x1, y0, z0), (x1, y1, z0), (x1, y1, z1), (x1, y0, z1)], 30),   # right
                 ([(x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)], 18)]   # top
        for corners, shade in faces:
            lines.append("\\draw[fill=black!%d,fill opacity=0.75,draw=black!60,very thin] %s;"
                         % (shade, poly(corners)))
    lines += draw_edges(res.tree, "sbBlue!40,line width=0.3pt", tr)
    lines += draw_path(res.path, "sbpath", tr)
    lines += draw_path(sc, "sbpathalt", tr)
    a, b = tr(s3), tr(g3)
    lines.append("\\node[sbstart] at (%s,%s) {};" % (f(a[0]), f(a[1])))
    lines.append("\\node[sbgoal] at (%s,%s) {};" % (f(b[0]), f(b[1])))
    lines.append("\\end{tikzpicture}")
    write("scene3d.tex", lines)
    print("3D: solution at iteration %d, %d vertices, raw length %.2f, "
          "shortcut %.2f, straight line %.2f"
          % (res.solution_iter, res.n_vertices, path_length(res.path),
             path_length(sc), np.linalg.norm(g3 - s3)))


# ----------------------------------------------------------------------
if __name__ == "__main__":
    os.makedirs(FIGDIR, exist_ok=True)
    os.makedirs(DATDIR, exist_ok=True)
    world = worked_example_world()
    res = tree_snapshots(world)
    print("worked example: solution at iteration %d; vertices at 50/200/1000: %s; "
          "path %d vertices, length %.3f"
          % (res.solution_iter, res.snapshots, len(res.path), path_length(res.path)))
    voronoi_figure()
    worst = statistics(world)
    jagged_figure(world, worst[0])
    connect_figure(world)
    shortcut_figure(world, res)
    scene3d_figure()
