"""Generate the two 5x5-grid figures of Chapter 3.

figures/ch03/grid-closed.tex        the closed set growing (4 snapshots)
figures/ch03/backward-heuristic.tex forward g from S next to backward h* to T

Both are computed with dijkstra_trace()/backward_dijkstra_heuristic() on
EXAMPLE_GRID from ch03_dijkstra.py, so every number matches the text.
Deterministic.  Run from Overleaf/:

    python3 code/figures/gen_ch03_grid_closed.py
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from ch03_dijkstra import (EXAMPLE_GRID, GridGraph, backward_dijkstra_heuristic,  # noqa: E402
                           dijkstra, dijkstra_trace, parse_grid, reconstruct_path)

FIGDIR = os.path.join(os.path.dirname(HERE), "..", "figures", "ch03")
SNAPSHOTS = [5, 10, 17, 19]          # number of expansions shown per panel


def fmt(x):
    return "%g" % x


def panel(lines, cells, cost, start, goal, closed, dist, path=None, values=None,
          title=None, xshift=0.0, styles=None):
    """Append one 5x5 panel; values overrides the cell labels (dict).

    styles (optional) maps a cell to an explicit TikZ fill style; cells
    without an entry are left white.  Without styles the fill follows the
    search state: settled cells grey, cells in the queue blue.
    """
    rows, cols = len(cells), len(cells[0])

    def y(r):
        return rows - 1 - r

    lines.append("\\begin{scope}[xshift=%.2fcm]" % xshift)
    closed_set = set(closed)
    for r in range(rows):
        for c in range(cols):
            v = (r, c)
            if cells[r][c]:
                lines.append("\\fill[sbobstacle] (%d,%d) rectangle ++(1,1);" % (c, y(r)))
                continue
            if styles is not None:
                if v in styles:
                    lines.append("\\fill[%s] (%d,%d) rectangle ++(1,1);" % (styles[v], c, y(r)))
            elif v in closed_set:
                lines.append("\\fill[sbclosed] (%d,%d) rectangle ++(1,1);" % (c, y(r)))
            elif v in dist:
                lines.append("\\fill[sbopen] (%d,%d) rectangle ++(1,1);" % (c, y(r)))
            if cost[r][c] > 1:
                lines.append("\\fill[pattern=north east lines,pattern color=sbOrange!70] (%d,%d) rectangle ++(1,1);" % (c, y(r)))
    lines.append("\\draw[black!40,very thin] (0,0) grid (%d,%d);" % (cols, rows))
    if path:
        pts = " -- ".join("(%.1f,%.1f)" % (c + 0.5, y(r) + 0.5) for r, c in path)
        lines.append("\\draw[sbpath,opacity=0.85] %s;" % pts)
    for r in range(rows):
        for c in range(cols):
            v = (r, c)
            label = None
            if values is not None:
                label = values.get(v)
            elif v in dist:
                label = dist[v]
            if label is not None:
                bold = "\\bfseries" if v in closed_set or values is not None else ""
                lines.append("\\node[font=\\scriptsize%s] at (%.1f,%.1f) {%s};"
                             % (bold, c + 0.5, y(r) + 0.5, fmt(label)))
    lines.append("\\draw[sbStart,line width=1.4pt] (%d,%d) rectangle ++(1,1);" % (start[1], y(start[0])))
    lines.append("\\draw[sbGoal,line width=1.4pt] (%d,%d) rectangle ++(1,1);" % (goal[1], y(goal[0])))
    lines.append("\\node[font=\\tiny,text=sbStart,anchor=north west,inner sep=1pt] at (%d,%d) {S};" % (start[1], y(start[0]) + 1))
    lines.append("\\node[font=\\tiny,text=sbGoal,anchor=north west,inner sep=1pt] at (%d,%d) {T};" % (goal[1], y(goal[0]) + 1))
    if title:
        lines.append("\\node[sbannot,anchor=north,align=center] at (%.1f,-0.15) {%s};" % (cols / 2, title))
    lines.append("\\end{scope}")


def legend(lines, y0):
    """Two legend rows below the panels (coordinates in grid units)."""
    items = [(0.0, y0, "sbclosed", "settled (\\Closed): final $\\gcost$"),
             (12.8, y0, "sbopen", "in the queue (\\Open): tentative $\\gcost$"),
             (0.0, y0 - 0.85, "hatch", "slow cell: entering it costs 3"),
             (12.8, y0 - 0.85, "sbobstacle", "obstacle")]
    for x, yy, style, text in items:
        if style == "hatch":
            lines.append("\\fill[pattern=north east lines,pattern color=sbOrange!70] (%.2f,%.2f) rectangle ++(0.5,0.5);" % (x, yy))
            lines.append("\\draw[black!40,very thin] (%.2f,%.2f) rectangle ++(0.5,0.5);" % (x, yy))
        else:
            lines.append("\\fill[%s] (%.2f,%.2f) rectangle ++(0.5,0.5);" % (style, x, yy))
        lines.append("\\node[sbannot,anchor=west,inner sep=2pt] at (%.2f,%.2f) {%s};" % (x + 0.55, yy + 0.25, text))


def main():
    cells, cost, start, goal = parse_grid(EXAMPLE_GRID)
    grid = GridGraph(cells, 4, cost)
    steps, dist_final, parent = dijkstra_trace(grid, start, goal)
    path = reconstruct_path(parent, goal)

    # Figure 1: the closed set growing.
    lines = ["% Generated by code/figures/gen_ch03_grid_closed.py -- do not edit",
             "\\begin{tikzpicture}[scale=0.62]"]
    for i, k in enumerate(SNAPSHOTS):
        step = steps[k - 1]
        # tentative values as they were after step k: replay the trace
        dist_k = {}
        for s in steps[:k]:
            g, u = s["popped"]
            if not s["stale"]:
                dist_k[u] = g
            for v, gn in s["relaxed"]:
                dist_k[v] = gn
        closed = step["closed"]
        gmax = max(dist_k[v] for v in closed)
        if k == SNAPSHOTS[-1]:
            title = "after %d expansions:\\\\ $T$ settled, $\\gcost(T)=%s$" % (k, fmt(dist_k[goal]))
        else:
            title = "after %d expansions:\\\\ all cells with $\\gcost \\le %s$ settled" % (k, fmt(gmax))
        panel(lines, cells, cost, start, goal, closed, dist_k,
              path=path if k == SNAPSHOTS[-1] else None, title=title, xshift=i * 6.4)
    legend(lines, -2.9)
    lines.append("\\end{tikzpicture}")
    out = os.path.join(FIGDIR, "grid-closed.tex")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(out))

    # Figure 2: forward g (full run) next to backward h*.
    g_all, _ = dijkstra(grid, start)
    h_star = backward_dijkstra_heuristic(grid, goal)
    lines = ["% Generated by code/figures/gen_ch03_grid_closed.py -- do not edit",
             "\\begin{tikzpicture}[scale=0.7]"]
    panel(lines, cells, cost, start, goal, [], g_all, values=g_all, styles={},
          title="forward from $S$: $\\gcost(v)=\\delta(S,v)$", xshift=0.0)
    panel(lines, cells, cost, start, goal, [], h_star, values=h_star, styles={},
          title="backward from $T$: $\\hcost^*(v)=\\delta(v,T)$", xshift=7.6)
    on_path = {v: g_all[v] + h_star[v] for v in g_all}
    optimal = {v: "sbGreen!25" for v in g_all if abs(on_path[v] - g_all[goal]) < 1e-9}
    panel(lines, cells, cost, start, goal, [], g_all, values=on_path, path=path,
          styles=optimal, title="$\\gcost(v)+\\hcost^*(v)$", xshift=15.2)
    lines.append("\\end{tikzpicture}")
    out = os.path.join(FIGDIR, "backward-heuristic.tex")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(out))
    print("h* on the grid:", {v: h_star[v] for v in sorted(h_star)})
    print("cells with g+h* = C*:", sorted(v for v in g_all if abs(on_path[v] - g_all[goal]) < 1e-9))


if __name__ == "__main__":
    main()
