#!/usr/bin/env python3
"""Draw the joint state space of two agents on a four-vertex graph.

Writes figures/ch11/joint-graph.tex: the single-agent graph (a path a-b-c
with a spur d at b) and its joint graph for two agents, a 4 x 4 lattice of
configurations in which the diagonal (both agents on the same vertex) is
crossed out, swap moves are drawn as missing (dotted red) edges and the
optimal joint path from (a, c) to (c, a), computed by joint A*, is
highlighted.  No randomness.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))
from ch11_mstar import Graph, MAPFInstance, collisions, joint_astar  # noqa: E402

OUT = os.path.join(HERE, "..", "..", "figures", "ch11", "joint-graph.tex")
VERTS = ["a", "b", "c", "d"]
POS = {"a": (0.0, 0.0), "b": (1.2, 0.0), "c": (2.4, 0.0), "d": (1.2, 1.2)}
STEP = 1.55          # lattice spacing of the joint graph


def main():
    graph = Graph.from_edges([("a", "b"), ("b", "c"), ("b", "d")])
    inst = MAPFInstance(graph, ["a", "c"], ["c", "a"])
    res = joint_astar(inst)
    path = res.path
    idx = {v: i for i, v in enumerate(VERTS)}

    def moves(v):
        return [v] + list(graph.neighbours(v))

    configs = [(p, q) for p in VERTS for q in VERTS]
    edges, swaps = set(), set()
    for p, q in configs:
        if p == q:
            continue
        for p2 in moves(p):
            for q2 in moves(q):
                if (p2, q2) == (p, q):
                    continue
                key = tuple(sorted([(p, q), (p2, q2)]))
                col = collisions((p, q), (p2, q2))
                if p2 == q2:
                    continue                       # vertex collision: no such node
                if col:
                    swaps.add(key)
                else:
                    edges.add(key)
    lines = []
    w = lines.append
    w("% Generated by code/figures/gen_ch11_joint_graph.py -- do not edit")
    w("\\begin{tikzpicture}[font=\\small,")
    w("  jnode/.style={circle,draw=sbBlue,fill=white,thick,inner sep=1pt,minimum size=17pt,font=\\scriptsize},")
    w("  jbad/.style={circle,draw=sbGray,fill=sbClosed,thin,inner sep=1pt,minimum size=17pt,font=\\scriptsize,text=sbGray},")
    w("  jedge/.style={draw=black!55,thick},")
    w("  jswap/.style={draw=sbRed,thick,dotted},")
    w("  jopt/.style={draw=sbPath,line width=2.2pt,opacity=0.9}]")
    # single-agent graph
    w("\\begin{scope}")
    for u, v in [("a", "b"), ("b", "c"), ("b", "d")]:
        w("\\draw[sbedge] (%.2f,%.2f) -- (%.2f,%.2f);" % (POS[u] + POS[v]))
    for v in VERTS:
        w("\\node[sbnode,minimum size=15pt] (g%s) at (%.2f,%.2f) {$%s$};" % ((v,) + POS[v] + (v,)))
    w("\\node[sbagentA,above left=1pt and -2pt of ga] {1};")
    w("\\node[sbagentB,above right=1pt and -2pt of gc] {2};")
    w("\\node[sbannot,align=center] at (1.2,-0.75) {the graph $G$: agent 1 goes $a\\to c$,\\\\ agent 2 goes $c\\to a$};")
    w("\\end{scope}")
    # joint graph
    x0 = 4.6
    w("\\begin{scope}[xshift=%.2fcm]" % x0)

    def coord(cfg):
        return (idx[cfg[0]] * STEP, idx[cfg[1]] * STEP)
    for key in sorted(edges):
        (p, q), (p2, q2) = key
        w("\\draw[jedge] (%.2f,%.2f) -- (%.2f,%.2f);" % (coord((p, q)) + coord((p2, q2))))
    for key in sorted(swaps):
        (p, q), (p2, q2) = key
        w("\\draw[jswap] (%.2f,%.2f) -- (%.2f,%.2f);" % (coord((p, q)) + coord((p2, q2))))
    for t in range(len(path) - 1):
        w("\\draw[jopt] (%.2f,%.2f) -- (%.2f,%.2f);" % (coord(path[t]) + coord(path[t + 1])))
    for p, q in configs:
        x, y = coord((p, q))
        if p == q:
            w("\\node[jbad] at (%.2f,%.2f) {$%s%s$};" % (x, y, p, q))
            w("\\draw[sbRed,thick] (%.2f,%.2f) -- (%.2f,%.2f);" % (x - 0.22, y - 0.22, x + 0.22, y + 0.22))
            w("\\draw[sbRed,thick] (%.2f,%.2f) -- (%.2f,%.2f);" % (x - 0.22, y + 0.22, x + 0.22, y - 0.22))
        else:
            w("\\node[jnode] at (%.2f,%.2f) {$%s%s$};" % (x, y, p, q))
    sx, sy = coord(path[0])
    gx, gy = coord(path[-1])
    w("\\node[sbstart,minimum size=22pt,fill opacity=0.35,text opacity=1] at (%.2f,%.2f) {};" % (sx, sy))
    w("\\node[sbgoal,minimum size=22pt,fill opacity=0.35,text opacity=1] at (%.2f,%.2f) {};" % (gx, gy))
    for t, cfg in enumerate(path):
        x, y = coord(cfg)
        w("\\node[font=\\tiny,text=sbBlue,anchor=south west,inner sep=1pt] at (%.2f,%.2f) {$t{=}%d$};"
          % (x + 0.16, y + 0.14, t))
    # axis labels
    for v in VERTS:
        w("\\node[sbannot,text=sbAgentA] at (%.2f,%.2f) {$%s$};" % (idx[v] * STEP, -0.7, v))
        w("\\node[sbannot,text=sbAgentB] at (%.2f,%.2f) {$%s$};" % (-0.7, idx[v] * STEP, v))
    w("\\node[sbannot,text=sbAgentA] at (%.2f,%.2f) {agent 1 at};" % (1.5 * STEP, -1.1))
    w("\\node[sbannot,text=sbAgentB,rotate=90] at (%.2f,%.2f) {agent 2 at};" % (-1.1, 1.5 * STEP))
    w("\\end{scope}")
    # legend
    lx, ly = x0 + 3.5 * STEP + 0.9, 3 * STEP
    w("\\draw[jedge] (%.2f,%.2f) -- ++(0.7,0); \\node[sbannot,anchor=west] at (%.2f,%.2f) {joint move};" % (lx, ly, lx + 0.8, ly))
    w("\\draw[jswap] (%.2f,%.2f) -- ++(0.7,0); \\node[sbannot,anchor=west,align=left] at (%.2f,%.2f) {swap: removed};" % (lx, ly - 0.55, lx + 0.8, ly - 0.55))
    w("\\draw[jopt] (%.2f,%.2f) -- ++(0.7,0); \\node[sbannot,anchor=west,align=left] at (%.2f,%.2f) {optimal joint path};" % (lx, ly - 1.1, lx + 0.8, ly - 1.1))
    w("\\node[jbad,minimum size=12pt] at (%.2f,%.2f) {}; \\node[sbannot,anchor=west,align=left] at (%.2f,%.2f) {vertex collision:\\\\ not a state};" % (lx + 0.35, ly - 1.75, lx + 0.8, ly - 1.75))
    w("\\end{tikzpicture}")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(OUT))
    print("configurations: %d valid, %d joint edges, %d swap edges removed, optimal cost %d, path %s"
          % (len(configs) - 4, len(edges), len(swaps), res.cost, path))


if __name__ == "__main__":
    main()
