#!/usr/bin/env python3
"""Assemble appendices/glossary.tex from the per-chapter term files.

Each chapter contributes appendices/glossary/<chNN>-terms.tex containing lines of the form
    \item[Term] One-sentence definition.
This script merges them, sorts alphabetically (case-insensitive, ignoring LaTeX markup),
keeps the first definition of a term that appears in several chapters (and records the
chapters that use it), and writes appendices/glossary.tex.  Run from the Overleaf folder.
"""
import glob, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "appendices", "glossary")
OUT = os.path.join(ROOT, "appendices", "glossary.tex")

item_re = re.compile(r"\\item\[(.*?)\]\s*(.*)")

def sort_key(term):
    t = re.sub(r"\\[a-zA-Z]+\*?(\[[^\]]*\])?(\{[^}]*\})?", lambda m: m.group(2)[1:-1] if m.group(2) else "", term)
    t = re.sub(r"[{}$^_]", "", t)
    return t.lower().strip()

entries = {}   # key -> (term, definition, [chapters])
order = []
for path in sorted(glob.glob(os.path.join(SRC, "*-terms.tex"))):
    chap = os.path.basename(path).split("-")[0]
    buf = None
    for line in open(path, encoding="utf-8"):
        line = line.rstrip("\n")
        if line.strip().startswith("%") or not line.strip():
            continue
        m = item_re.match(line.strip())
        if m:
            if buf: entries_add = buf
            term, definition = m.group(1).strip(), m.group(2).strip()
            key = sort_key(term)
            if key in entries:
                entries[key][2].append(chap)
            else:
                entries[key] = [term, definition, [chap]]
                order.append(key)
            buf = key
        elif buf:  # continuation line of a definition
            entries[buf][1] += " " + line.strip()

def chap_label(ch):
    return ch  # e.g. ch04 -> \cref{ch:ch04}

lines = [
    "\\chapter{Glossary}",
    "\\markboth{Glossary}{Glossary}",
    "% Generated by tools/assemble_glossary.py from appendices/glossary/*-terms.tex. Do not edit by hand;",
    "% edit the per-chapter term files and re-run the script.",
    "This glossary collects the terms that the book sets in bold when it defines them. Each entry",
    "names the chapter that introduces the term; a term used in several chapters points to the first.",
    "",
    "\\begin{description}[style=nextline,leftmargin=1.5em,itemsep=2pt]",
]
for key in sorted(order, key=lambda k: sort_key(entries[k][0])):
    term, definition, chaps = entries[key]
    refs = ", ".join("\\cref{ch:%s}" % c for c in dict.fromkeys(chaps))
    if not definition.rstrip().endswith((".", "?", "!")):
        definition = definition.rstrip() + "."
    lines.append("\\item[%s] %s \\ (%s)" % (term, definition, refs))
lines.append("\\end{description}")
open(OUT, "w", encoding="utf-8").write("\n".join(lines) + "\n")
print("glossary: %d terms from %d files -> %s" % (len(order), len(glob.glob(os.path.join(SRC, '*-terms.tex'))), os.path.relpath(OUT, ROOT)))
